# Generated by Django 2.2.6 on 2020-11-14 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('sender_last_name', models.CharField(blank=True, max_length=50, verbose_name='Last name')),
                ('sender_contact', models.IntegerField(verbose_name='Contact')),
                ('receiver_first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('receiver_last_name', models.CharField(blank=True, max_length=50, verbose_name='Last name')),
                ('receiver_contact', models.IntegerField(verbose_name='Contact')),
                ('items', models.TextField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('rider', models.CharField(max_length=100)),
                ('delivery_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date')),
                ('departure', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('arrival', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delivery_status', models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('remarks', models.TextField(blank=True, max_length=255, null=True)),
                ('added_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Entry Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
    ]
