# Generated by Django 2.2.6 on 2020-11-26 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jskdelivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
